# Generated by Django 5.2 on 2025-05-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transction',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
